#!/usr/bin/env bash
set -e
set -u
set -o pipefail

# Copy stdin to the system clipboard, trimming a trailing newline.

if hash pbcopy 2>/dev/null; then
	cmd='pbcopy'
elif hash xclip 2>/dev/null; then
	cmd='xclip -selection clipboard'
else
	echo 'cannot find a copy program' >&2
	exit 1
fi

exec perl -pe 'chomp if eof' | $cmd
