#!/usr/bin/env bash
set -e
set -u
set -o pipefail

# Watch the clipboard and print each new value as it's copied.
# Useful for doing stuff as new clipboard content comes in.
# E.g.: pastas | wget -i -

trap 'exit 0' SIGINT

last_value=''

while true
do
  value="$(pasta)"

  if [ "$last_value" != "$value" ]; then
    echo "$value"
    last_value="$value"
  fi

  sleep 0.1
done
